// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: server/minsim/minsim.proto

package minsim

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MinsimClient is the client API for Minsim service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MinsimClient interface {
	NewPost(ctx context.Context, in *NewMinsimRequest, opts ...grpc.CallOption) (*NewMinsimResponse, error)
}

type minsimClient struct {
	cc grpc.ClientConnInterface
}

func NewMinsimClient(cc grpc.ClientConnInterface) MinsimClient {
	return &minsimClient{cc}
}

func (c *minsimClient) NewPost(ctx context.Context, in *NewMinsimRequest, opts ...grpc.CallOption) (*NewMinsimResponse, error) {
	out := new(NewMinsimResponse)
	err := c.cc.Invoke(ctx, "/server.minsim.Minsim/NewPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinsimServer is the server API for Minsim service.
// All implementations must embed UnimplementedMinsimServer
// for forward compatibility
type MinsimServer interface {
	NewPost(context.Context, *NewMinsimRequest) (*NewMinsimResponse, error)
	mustEmbedUnimplementedMinsimServer()
}

// UnimplementedMinsimServer must be embedded to have forward compatible implementations.
type UnimplementedMinsimServer struct {
}

func (UnimplementedMinsimServer) NewPost(context.Context, *NewMinsimRequest) (*NewMinsimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewPost not implemented")
}
func (UnimplementedMinsimServer) mustEmbedUnimplementedMinsimServer() {}

// UnsafeMinsimServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MinsimServer will
// result in compilation errors.
type UnsafeMinsimServer interface {
	mustEmbedUnimplementedMinsimServer()
}

func RegisterMinsimServer(s grpc.ServiceRegistrar, srv MinsimServer) {
	s.RegisterService(&Minsim_ServiceDesc, srv)
}

func _Minsim_NewPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMinsimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinsimServer).NewPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.minsim.Minsim/NewPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinsimServer).NewPost(ctx, req.(*NewMinsimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Minsim_ServiceDesc is the grpc.ServiceDesc for Minsim service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Minsim_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.minsim.Minsim",
	HandlerType: (*MinsimServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewPost",
			Handler:    _Minsim_NewPost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/minsim/minsim.proto",
}
